version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - .:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
    depends_on:
      - backend

  backend:
    build:
      context: ./payment_backend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./payment_backend:/app
      - /app/node_modules
    environment:
      - NODE_ENV=development
      - PORT=3000
      - PAYSTACK_SECRET_KEY=${PAYSTACK_SECRET_KEY}
      - MONGODB_URI=${MONGODB_URI}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
    env_file:
      - ./payment_backend/.env