
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://dxpsaqosxnlbhuasqnkp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImR4cHNhcW9zeG5sYmh1YXNxbmtwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE3ODgwNTMsImV4cCI6MjA2NzM2NDA1M30.mgvhPTiTofcTq86mrSQI5S1mvzi-7nQ5Z15-9ipWxko";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
